## numpy

In [1]:
import numpy as np

- np.expand_dims

In [3]:
x = np.array([1,2])
x.shape

(2,)

In [6]:
y=np.expand_dims(x, axis=0) # expand by row
y.shape

(1, 2)

In [7]:
y

array([[1, 2]])

In [11]:
# equivalent to x[np.newaxis]
x[np.newaxis]

array([[1, 2]])

In [8]:
y=np.expand_dims(x, axis=1) # expand by column
y.shape

(2, 1)

In [9]:
y

array([[1],
       [2]])

In [10]:
x[np.newaxis]

array([[1, 2]])

## pandas